name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your default branch name if different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 # Use a Ruby version compatible with Jekyll 3.x
        bundler-cache: true

    # Step 3: Update Bundler
    - name: Update Bundler
      run: |
        gem install bundler

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        bundle install

    # Step 5: Build the Jekyll site
    - name: Build the site
      run: |
        bundle exec jekyll build

    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site