name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your default branch name if different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Use a Ruby version compatible with Jekyll
        bundler-cache: true

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        bundle install

    # Step 4: Build the Jekyll site
    - name: Build the site
      run: |
        bundle exec jekyll build

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site