title: Garmin Connect Activities
description: Garmin Connect Activities
baseurl: /Garmin-Connect-Activities        # Include repo name for project pages
url: https://bhyman67.github.io

plugins:
  - jekyll-mermaid
  - jekyll-seo-tag
  - github-pages

theme: minima

mermaid:
  startOnLoad: true