title: Garmin Connect Activities
description: Garmin Connect Activities
baseurl: /Garmin-Connect-Activities        # Include repo name for project pages
url: https://bhyman67.github.io

plugins:
  - jekyll-mermaid
  - github-pages
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache

theme: minima

mermaid:
  startOnLoad: true