name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - gh-pages  
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1  # Ruby 3.1 is compatible with Jekyll 4.4.1
        bundler-cache: true

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        bundle install

    # Step 4: Build the Jekyll site in production mode
    - name: Build the site
      run: |
        JEKYLL_ENV=production bundle exec jekyll build

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
