name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main     # Change this to 'main' if `gh-pages` is your deployment branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Build the Jekyll site in production mode
      run: JEKYLL_ENV=production bundle exec jekyll build

    - name: Add .nojekyll file
      run: touch ./_site/.nojekyll

    - name: Verify _site folder
      run: ls -la ./_site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
